# Generated by Django 3.1.2 on 2020-10-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='dateCreate',
            new_name='photoDate',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='info',
            new_name='photoInfo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='result',
            new_name='photoResult',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='url',
            new_name='photoUrl',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photoId',
        ),
    ]
